/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projetocalcemjava;

public class App {
    public String salve() {
        return "Salve Rapaziada";
    }

    public static void main(String[] args) {
        Calculadora calc = new Calculadora();
        System.out.println(calc.somar(30, 6));
        System.out.println(calc.sub(30, 6));
        System.out.println(calc.mult(30, 6));
        System.out.println(calc.div(30, 6));
    }
}
